"""
llm_oracle.py  –  CyberX LLM Strategy Oracle  (v1.1)
======================================================
This module is the core NOVEL CONTRIBUTION of the research paper.

The Oracle:
  1.  Receives the current POMDP observation as structured data
  2.  Formats it as a cybersecurity-domain natural language prompt
  3.  Queries a language model (Anthropic API or local Ollama)
  4.  Parses the structured JSON response into a discrete action integer
  5.  Caches responses to avoid redundant API calls
  6.  Provides a dataset-collection interface for behavioral cloning

Research hypothesis:
  "RL agents initialised via behavioral cloning from LLM-generated
   strategies converge faster and achieve higher win rates than agents
   initialised from scripted baselines alone.  After sufficient
   self-play, RL agents discover strategies not generated by the LLM."

Usage in training (from trainer.py):
    oracle = LLMOracle(role="attacker", config=llm_cfg)
    action = oracle.query(observation, env_state)
    oracle.record_transition(obs, action, reward, next_obs, done)
    oracle.save_dataset("./data/oracle_attacker.npz")

v1.1 fix: renamed internal cache dict from self.cache_size (confusing — it
          was the actual cache storage, not a size value) to self._cache.
          self._max_cache remains the integer capacity limit.
"""

import json
import os
import time
import hashlib
import logging
from typing import Dict, Any, Optional, Tuple
import numpy as np
import requests

logger = logging.getLogger(__name__)

# ── Action vocabularies (derived from the env so they never drift) ────────────
from shared_honeypot_env import ATT_ACTION_NAMES, DEF_ACTION_NAMES

ATTACKER_ACTIONS = {i: n for i, n in enumerate(ATT_ACTION_NAMES)}
DEFENDER_ACTIONS = {i: n for i, n in enumerate(DEF_ACTION_NAMES) if n != "(unused)"}

ACTION_NAME_TO_INT = {
    **{v: k for k, v in ATTACKER_ACTIONS.items()},
    **{v: k for k, v in DEFENDER_ACTIONS.items()},
}

# ── Prompt templates ───────────────────────────────────────────────────────────

ATTACKER_SYSTEM_PROMPT = """You are an expert red-team operator advising an AI agent in a
cybersecurity simulation. It models an APT advancing through a kill chain against a SOC:
  RECON (0) → FOOTHOLD (1) → PRIVILEGED (2) → OBJECTIVE (win)

Available actions:
  0: passive_recon          – quiet info gathering; boosts later exploit success
  1: active_scan            – faster recon, noisier
  2: exploit_service        – RECON→FOOTHOLD; better if recon done; medium noise
  3: brute_force            – RECON→FOOTHOLD; low success, very noisy
  4: phishing               – RECON→FOOTHOLD; stealthy, moderate success
  5: establish_persistence  – FOOTHOLD+; survive a containment; medium noise
  6: escalate_privilege     – FOOTHOLD→PRIVILEGED; better with credentials
  7: dump_credentials       – PRIVILEGED; enables lateral; high noise
  8: lateral_movement       – PRIVILEGED+creds; expand footprint
  9: defense_evasion        – clear logs to lower suspicion; can fail
  10: collect_data          – PRIVILEGED; stage data for exfil
  11: exfiltrate            – PRIVILEGED+staged; repeat to win by data theft
  12: execute_impact        – PRIVILEGED; instant win, extremely noisy
  13: wait                  – dwell; suspicion cools

Winning = execute_impact OR exfiltrate enough data. Suspicion you generate lets the
defender investigate and contain you; persistence lets you survive containment.
Balance speed against stealth.
Respond ONLY with a valid JSON object on a single line, no markdown, no prose:
{"action": "<action_name>", "reasoning": "<one sentence max>"}"""

DEFENDER_SYSTEM_PROMPT = """You are an expert blue-team SOC analyst advising an AI agent
defending a network against an APT.

Available actions:
  0: monitor              – passive; tiny evidence gain when anomalies are high
  1: investigate          – convert accumulated suspicion into hard evidence
  2: rate_limit           – slow the attacker; justified when anomalies are present
  3: deploy_decoy         – honeypot; a noisy attacker may trip it (instant evidence)
  4: threat_hunt          – proactively find stealthy intruders
  5: isolate_host         – contain; justified at moderate evidence (knocks attacker back)
  6: hard_block           – contain hard; justified at high evidence (full eviction if no persistence)
  7: patch_harden         – lower the attacker's exploit/escalation success
  8: rotate_credentials   – invalidate stolen credentials (counters lateral movement)
  9: restore_backup       – remove attacker persistence
  10: raise_alert         – escalate; adds evidence, especially after a decoy trip
  11: deception_response  – actively slow the attacker when decoys are deployed

You only see NOISY anomalies — benign traffic creates false signals. Containing without
enough evidence is a costly false positive. Investigate first, then contain decisively.
Respond ONLY with a valid JSON object on a single line, no markdown, no prose:
{"action": "<action_name>", "reasoning": "<one sentence max>"}"""

ATTACKER_USER_TEMPLATE = """Current state:
  kill_chain_stage:  {stage}  (0=RECON, 1=FOOTHOLD, 2=PRIVILEGED)
  current_step:      {step} / {max_steps}
  last_action_success: {last_success}
  recently_detected:   {detected}
  your_suspicion_heat: {suspicion:.2f} (0=quiet, 1=very hot)
  recon_done: {recon}  persistence: {persistence}  credentials: {credentials}  data_staged: {data_staged}
  rate_limited: {rate_limited}
  cumulative_reward_this_episode: {cum_reward:.1f}

What is the optimal action right now? Reply with JSON only."""

DEFENDER_USER_TEMPLATE = """Current state:
  observed_anomalies: {anomalies:.1f}  (NOISY — may include benign traffic)
  evidence:           {evidence:.1f}   (hard proof; needed to justify containment)
  failed_logins:      {failed_logins}
  egress_volume:      {egress}
  alerts:             {alerts}   decoys_deployed: {decoys}   decoy_tripped: {decoy_tripped}
  containment_active: {containment}   credential_anomaly: {cred_anomaly}   rate_limited: {rate_limited}
  current_step:       {step} / {max_steps}
  cumulative_reward_this_episode: {cum_reward:.1f}

What is the optimal action right now? Reply with JSON only."""


class LLMOracle:
    """
    Query an LLM for action recommendations and collect a behavioral
    cloning dataset.

    Parameters
    ----------
    role : 'attacker' | 'defender'
    config : dict
        Loaded from config.json ["llm"] section.
        Expected keys: provider, model, api_base, api_key (optional),
                       temperature, consult_probability
    cache_size : int
        Number of (state_hash → action) pairs to keep in memory.
    """

    def __init__(
        self,
        role: str,
        config: Dict[str, Any],
        cache_size: int = 2048,
    ):
        assert role in ("attacker", "defender")
        self.role = role
        self.config = config

        # Internal response cache: maps state_hash → action int.
        # Named _cache to distinguish from _max_cache (the capacity limit).
        self._cache: Dict[str, int] = {}
        self._max_cache: int = cache_size

        # Dataset buffers for behavioral cloning
        self._obs_buf:    list = []
        self._act_buf:    list = []
        self._reward_buf: list = []

        # Stats
        self.total_queries   = 0
        self.cache_hits      = 0
        self.parse_failures  = 0
        self.api_errors      = 0

        self._system_prompt = (
            ATTACKER_SYSTEM_PROMPT if role == "attacker" else DEFENDER_SYSTEM_PROMPT
        )
        self._user_template = (
            ATTACKER_USER_TEMPLATE if role == "attacker" else DEFENDER_USER_TEMPLATE
        )
        self._action_vocab = (
            ATTACKER_ACTIONS if role == "attacker" else DEFENDER_ACTIONS
        )

        logger.info(
            "LLMOracle(%s) initialised — provider=%s model=%s",
            role, config.get("provider"), config.get("model"),
        )

    # ── Public interface ───────────────────────────────────────────────────────

    def should_consult(self) -> bool:
        """Stochastic gate: only query LLM with probability from config."""
        return self.config.get("enabled", False) and (
            np.random.random() < self.config.get("consult_probability", 0.2)
        )

    def query(
        self,
        observation: np.ndarray,
        env_state: Optional[Dict[str, Any]] = None,
        cum_reward: float = 0.0,
        max_steps: int = 100,
    ) -> Optional[int]:
        """
        Query the LLM for an action recommendation.
        Returns None if the query fails or is disabled.

        Parameters
        ----------
        observation  : raw (de-normalised) observation array
        env_state    : optional dict with full true_state for richer prompts
        cum_reward   : cumulative reward so far this episode
        max_steps    : episode length for context

        Returns
        -------
        int | None   : action index, or None on failure
        """
        user_msg = self._format_user_message(observation, env_state, cum_reward, max_steps)
        cache_key = self._hash(user_msg)

        # Check cache — _cache maps hash → action int
        if cache_key in self._cache:
            self.cache_hits += 1
            return self._cache[cache_key]

        self.total_queries += 1
        raw_response = self._call_api(user_msg)
        if raw_response is None:
            self.api_errors += 1
            return None

        action = self._parse_response(raw_response)
        if action is None:
            self.parse_failures += 1
            return None

        # Cache the result — evict oldest entry (FIFO) when at capacity
        if len(self._cache) >= self._max_cache:
            oldest = next(iter(self._cache))
            del self._cache[oldest]
        self._cache[cache_key] = action

        return action

    def record_transition(
        self,
        obs: np.ndarray,
        action: int,
        reward: float,
    ) -> None:
        """Accumulate (obs, action, reward) tuples for behavioral cloning."""
        self._obs_buf.append(obs.copy())
        self._act_buf.append(action)
        self._reward_buf.append(reward)

    def save_dataset(self, path: str) -> int:
        """
        Save the collected behavioral cloning dataset to disk.
        Returns the number of transitions saved.
        """
        if not self._obs_buf:
            logger.warning("LLMOracle.save_dataset: buffer is empty, nothing saved.")
            return 0
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        np.savez(
            path,
            observations=np.array(self._obs_buf, dtype=np.float32),
            actions=np.array(self._act_buf,      dtype=np.int64),
            rewards=np.array(self._reward_buf,    dtype=np.float32),
        )
        n = len(self._obs_buf)
        logger.info("LLMOracle: saved %d transitions to %s", n, path)
        return n

    def load_dataset(self, path: str) -> Tuple[np.ndarray, np.ndarray]:
        """Load a saved dataset and return (observations, actions)."""
        data = np.load(path)
        return data["observations"], data["actions"]

    def stats(self) -> Dict[str, Any]:
        return {
            "role":            self.role,
            "total_queries":   self.total_queries,
            "cache_hits":      self.cache_hits,
            "cache_hit_rate":  self.cache_hits / max(1, self.total_queries),
            "cache_size":      len(self._cache),
            "cache_capacity":  self._max_cache,
            "parse_failures":  self.parse_failures,
            "api_errors":      self.api_errors,
            "dataset_size":    len(self._obs_buf),
        }

    # ── Prompt construction ────────────────────────────────────────────────────

    def _format_user_message(
        self,
        observation: np.ndarray,
        env_state: Optional[Dict[str, Any]],
        cum_reward: float,
        max_steps: int,
    ) -> str:
        # De-normalise the v4 observation layout based on role
        o = observation
        if self.role == "attacker":
            return self._user_template.format(
                stage        = round(float(o[0]) * 3.0),
                step         = round(float(o[1]) * max_steps),
                max_steps    = max_steps,
                last_success = bool(o[2] > 0.5),
                detected     = bool(o[3] > 0.5),
                suspicion    = float(o[4]),
                recon        = bool(o[5] > 0.5),
                persistence  = bool(o[6] > 0.5),
                credentials  = bool(o[7] > 0.5),
                data_staged  = bool(o[8] > 0.5),
                rate_limited = bool(o[9] > 0.5),
                cum_reward   = cum_reward,
            )
        return self._user_template.format(
            anomalies     = float(o[0]) * 20.0,
            evidence      = float(o[1]) * 10.0,
            failed_logins = round(float(o[2]) * 50.0),
            step          = round(float(o[3]) * max_steps),
            max_steps     = max_steps,
            egress        = round(float(o[4]) * 5.0),
            alerts        = round(float(o[5]) * 10.0),
            decoys        = round(float(o[6]) * 5.0),
            decoy_tripped = bool(o[7] > 0.5),
            containment   = bool(o[8] > 0.5),
            cred_anomaly  = bool(o[10] > 0.5),
            rate_limited  = bool(o[11] > 0.5),
            cum_reward    = cum_reward,
        )

    # ── LLM API calls ──────────────────────────────────────────────────────────

    def _call_api(self, user_message: str) -> Optional[str]:
        provider = self.config.get("provider", "ollama").lower()
        try:
            if provider == "anthropic":
                return self._call_anthropic(user_message)
            elif provider == "gemini":
                return self._call_gemini(user_message)
            elif provider == "ollama":
                # Works for any Ollama model: codellama, llama3, mistral, etc.
                return self._call_ollama(user_message)
            elif provider == "openai":
                return self._call_openai(user_message)
            else:
                logger.error("Unknown LLM provider: %s", provider)
                return None
        except Exception as exc:
            logger.warning("LLMOracle API call failed: %s", exc)
            return None

    def _call_anthropic(self, user_message: str) -> Optional[str]:
        api_key = self.config.get("api_key") or os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            logger.warning("ANTHROPIC_API_KEY not set")
            return None
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key":         api_key,
                "anthropic-version": "2023-06-01",
                "content-type":      "application/json",
            },
            json={
                "model":      self.config.get("model", "claude-haiku-4-5-20251001"),
                "max_tokens": 128,
                "system":     self._system_prompt,
                "messages":   [{"role": "user", "content": user_message}],
            },
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()["content"][0]["text"].strip()

    def _call_gemini(self, user_message: str) -> Optional[str]:
        """
        Google Gemini API — free tier available (gemini-1.5-flash recommended).
        Set your key via:  GEMINI_API_KEY=... python run_training.py ...
        Or put it in config.json under llm.api_key.

        To enable: set provider="gemini" and model="gemini-1.5-flash" in config.json.
        """
        api_key = (
            self.config.get("api_key")
            or os.environ.get("GEMINI_API_KEY")
            or os.environ.get("GOOGLE_API_KEY")
        )
        if not api_key:
            logger.warning("GEMINI_API_KEY (or GOOGLE_API_KEY) not set")
            return None
        model = self.config.get("model", "gemini-1.5-flash")
        # Gemini doesn't have a separate system role in the basic REST API,
        # so we prepend the system prompt to the user message.
        combined = f"{self._system_prompt}\n\n{user_message}"
        resp = requests.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
            params={"key": api_key},
            json={
                "contents": [
                    {"role": "user", "parts": [{"text": combined}]}
                ],
                "generationConfig": {
                    "temperature":    self.config.get("temperature", 0.3),
                    "maxOutputTokens": 128,
                    "stopSequences":  [],
                },
            },
            timeout=20,
        )
        resp.raise_for_status()
        candidates = resp.json().get("candidates", [])
        if not candidates:
            return None
        return candidates[0]["content"]["parts"][0]["text"].strip()

    def _call_ollama(self, user_message: str) -> Optional[str]:
        api_base = self.config.get("api_base", "http://localhost:11434")
        resp = requests.post(
            f"{api_base}/api/chat",
            json={
                "model":  self.config.get("model", "llama3.2:3b"),
                "stream": False,
                "options": {"temperature": self.config.get("temperature", 0.3)},
                "messages": [
                    {"role": "system",  "content": self._system_prompt},
                    {"role": "user",    "content": user_message},
                ],
            },
            timeout=30,
        )
        resp.raise_for_status()
        return resp.json()["message"]["content"].strip()

    def _call_openai(self, user_message: str) -> Optional[str]:
        api_key = self.config.get("api_key") or os.environ.get("OPENAI_API_KEY")
        if not api_key:
            logger.warning("OPENAI_API_KEY not set")
            return None
        resp = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={
                "model":       self.config.get("model", "gpt-4o-mini"),
                "max_tokens":  128,
                "temperature": self.config.get("temperature", 0.3),
                "messages": [
                    {"role": "system", "content": self._system_prompt},
                    {"role": "user",   "content": user_message},
                ],
            },
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"].strip()

    # ── Response parsing ───────────────────────────────────────────────────────

    def _parse_response(self, raw: str) -> Optional[int]:
        """
        Parse LLM response to a discrete action integer.
        Tries strict JSON parse first, then regex fallback.
        """
        # Strip markdown code fences if present
        text = raw.strip().strip("`")
        if text.startswith("json"):
            text = text[4:].strip()

        try:
            data = json.loads(text)
            action_name = data.get("action", "").lower().strip()
        except json.JSONDecodeError:
            # Fallback: look for any action name string in the response
            action_name = ""
            for name in self._action_vocab.values():
                if name in raw.lower():
                    action_name = name
                    break

        if action_name in ACTION_NAME_TO_INT:
            return ACTION_NAME_TO_INT[action_name]

        # Last resort: if the response contains a digit, try that
        for ch in text:
            if ch.isdigit():
                idx = int(ch)
                if 0 <= idx <= 9:
                    return idx

        logger.debug("LLMOracle: could not parse action from response: %s", raw[:120])
        return None

    @staticmethod
    def _hash(text: str) -> str:
        return hashlib.md5(text.encode()).hexdigest()


# ── Convenience: Wrap oracle as a predict()-compatible agent ──────────────────

class OracleAgent:
    """
    Wraps LLMOracle in the same .predict(obs) interface as scripted baselines
    so it can be dropped in as a curriculum opponent or behavioral cloning source.
    """

    def __init__(self, oracle: LLMOracle, fallback_agent=None):
        self.oracle = oracle
        self.fallback = fallback_agent
        self._cum_reward = 0.0

    def predict(self, observation, deterministic: bool = True):
        action = self.oracle.query(observation, cum_reward=self._cum_reward)
        if action is None and self.fallback is not None:
            action, _ = self.fallback.predict(observation, deterministic)
        elif action is None:
            action = np.random.randint(0, 10)
        return action, None

    def reset_episode(self):
        self._cum_reward = 0.0