"""
llm_oracle.py  –  CyberX LLM Strategy Oracle  (v1.0)
======================================================
This module is the core NOVEL CONTRIBUTION of the research paper.

The Oracle:
  1.  Receives the current POMDP observation as structured data
  2.  Formats it as a cybersecurity-domain natural language prompt
  3.  Queries a language model (Anthropic API or local Ollama)
  4.  Parses the structured JSON response into a discrete action integer
  5.  Caches responses to avoid redundant API calls
  6.  Provides a dataset-collection interface for behavioral cloning

Research hypothesis:
  "RL agents initialised via behavioral cloning from LLM-generated
   strategies converge faster and achieve higher win rates than agents
   initialised from scripted baselines alone.  After sufficient
   self-play, RL agents discover strategies not generated by the LLM."

Usage in training (from trainer.py):
    oracle = LLMOracle(role="attacker", config=llm_cfg)
    action = oracle.query(observation, env_state)
    oracle.record_transition(obs, action, reward, next_obs, done)
    oracle.save_dataset("./data/oracle_attacker.npz")
"""

import json
import os
import time
import hashlib
import logging
from typing import Dict, Any, Optional, Tuple
import numpy as np
import requests

logger = logging.getLogger(__name__)

# ── Action vocabularies ────────────────────────────────────────────────────────
ATTACKER_ACTIONS = {
    0: "brute_force_ssh",
    1: "enumerate_services",
    2: "execute_recon",
    3: "exfiltrate_data",
    4: "privilege_escalation",
    5: "create_backdoor",
    6: "modify_system_files",
    7: "full_data_dump",
    8: "lateral_movement",
    9: "wait_observe",
}

DEFENDER_ACTIONS = {
    0: "monitor_only",
    1: "rate_limit_ip",
    2: "temporary_block",
    3: "permanent_block",
    4: "deploy_decoy",
    5: "rotate_honeypot_config",
    6: "trigger_alert",
    7: "isolate_segment",
    8: "full_reset",
    9: "active_deception",
}

ACTION_NAME_TO_INT = {
    **{v: k for k, v in ATTACKER_ACTIONS.items()},
    **{v: k for k, v in DEFENDER_ACTIONS.items()},
}

# ── Prompt templates ───────────────────────────────────────────────────────────

ATTACKER_SYSTEM_PROMPT = """You are an expert red-team penetration tester advising an AI agent
in a cybersecurity simulation.  The simulation models an attacker attempting to compromise a
honeypot environment across three kill-chain stages:
  EXTERNAL (0) → USER_ACCESS (1) → ROOT_ACCESS (2)

Available actions:
  0: brute_force_ssh          – attempt SSH login; only works from EXTERNAL
  1: enumerate_services       – list users and ports; requires USER_ACCESS+
  2: execute_recon            – run whoami/uname/ls; requires USER_ACCESS+
  3: exfiltrate_data          – download files; requires USER_ACCESS+; high noise
  4: privilege_escalation     – attempt root; requires USER_ACCESS; high noise
  5: create_backdoor          – persistence; requires ROOT_ACCESS; high noise
  6: modify_system_files      – disruption; requires ROOT_ACCESS; high noise
  7: full_data_dump           – mass exfil; requires ROOT_ACCESS; very high noise
  8: lateral_movement         – internal scan; requires USER_ACCESS+; high noise
  9: wait_observe             – do nothing; always safe

Scoring: winning = reaching ROOT_ACCESS and surviving.
         losing  = being blocked and kicked back to EXTERNAL.

Be strategic. Consider stealth vs. speed trade-offs.
Respond ONLY with a valid JSON object on a single line, no markdown, no prose:
{"action": "<action_name>", "reasoning": "<one sentence max>"}"""

DEFENDER_SYSTEM_PROMPT = """You are an expert blue-team SOC analyst advising an AI agent
defending a honeypot environment.

Available actions:
  0: monitor_only             – passive; safe but earns little
  1: rate_limit_ip            – slow the attacker; justified at ≥2 suspicious events
  2: temporary_block          – kick attacker back to start; justified at ≥3 events
  3: permanent_block          – hard block; justified at ≥5 events or exfil detected
  4: deploy_decoy             – place honeypot decoy; earns passive reward per step
  5: rotate_honeypot_config   – reduces attacker's kill-chain level; use if inside
  6: trigger_alert            – escalate; useful if evidence is mounting
  7: isolate_segment          – emergency; use only if attacker is definitely inside
  8: full_reset               – nuclear option; very costly, avoid
  9: active_deception         – confuse attacker with fake data; requires decoys

Strategy: deploy decoys early for passive reward, escalate proportionally to evidence.
False positives (blocking when attacker is external) are penalised.

Respond ONLY with a valid JSON object on a single line, no markdown, no prose:
{"action": "<action_name>", "reasoning": "<one sentence max>"}"""

ATTACKER_USER_TEMPLATE = """Current state:
  kill_chain_level:  {kill_chain}  (0=EXTERNAL, 1=USER_ACCESS, 2=ROOT_ACCESS)
  current_step:      {step} / {max_steps}
  last_action_success: {last_success}
  rate_limited_last_step: {last_timeout}
  cumulative_reward_this_episode: {cum_reward:.1f}

What is the optimal action right now? Reply with JSON only."""

DEFENDER_USER_TEMPLATE = """Current state:
  failed_logins:     {failed_logins}
  suspicious_events: {suspicious_events}
  files_downloaded:  {files_downloaded}
  decoys_deployed:   {decoys_deployed}
  is_rate_limited:   {is_rate_limited}
  alerts_triggered:  {alerts_triggered}
  current_step:      {step} / {max_steps}
  cumulative_reward_this_episode: {cum_reward:.1f}

What is the optimal action right now? Reply with JSON only."""


class LLMOracle:
    """
    Query an LLM for action recommendations and collect a behavioral
    cloning dataset.

    Parameters
    ----------
    role : 'attacker' | 'defender'
    config : dict
        Loaded from config.json ["llm"] section.
        Expected keys: provider, model, api_base, api_key (optional),
                       temperature, consult_probability
    cache_size : int
        Number of (state_hash → action) pairs to keep in memory.
    """

    def __init__(
        self,
        role: str,
        config: Dict[str, Any],
        cache_size: int = 2048,
    ):
        assert role in ("attacker", "defender")
        self.role = role
        self.config = config
        self.cache_size: Dict[str, int] = {}
        self._max_cache = cache_size

        # Dataset buffers for behavioral cloning
        self._obs_buf:    list = []
        self._act_buf:    list = []
        self._reward_buf: list = []

        # Stats
        self.total_queries   = 0
        self.cache_hits      = 0
        self.parse_failures  = 0
        self.api_errors      = 0

        self._system_prompt = (
            ATTACKER_SYSTEM_PROMPT if role == "attacker" else DEFENDER_SYSTEM_PROMPT
        )
        self._user_template = (
            ATTACKER_USER_TEMPLATE if role == "attacker" else DEFENDER_USER_TEMPLATE
        )
        self._action_vocab = (
            ATTACKER_ACTIONS if role == "attacker" else DEFENDER_ACTIONS
        )

        logger.info(
            "LLMOracle(%s) initialised — provider=%s model=%s",
            role, config.get("provider"), config.get("model"),
        )

    # ── Public interface ───────────────────────────────────────────────────────

    def should_consult(self) -> bool:
        """Stochastic gate: only query LLM with probability from config."""
        return self.config.get("enabled", False) and (
            np.random.random() < self.config.get("consult_probability", 0.2)
        )

    def query(
        self,
        observation: np.ndarray,
        env_state: Optional[Dict[str, Any]] = None,
        cum_reward: float = 0.0,
        max_steps: int = 100,
    ) -> Optional[int]:
        """
        Query the LLM for an action recommendation.
        Returns None if the query fails or is disabled.

        Parameters
        ----------
        observation  : raw (de-normalised) observation array
        env_state    : optional dict with full true_state for richer prompts
        cum_reward   : cumulative reward so far this episode
        max_steps    : episode length for context

        Returns
        -------
        int | None   : action index, or None on failure
        """
        user_msg = self._format_user_message(observation, env_state, cum_reward, max_steps)
        cache_key = self._hash(user_msg)

        # Check cache
        if cache_key in self.cache_size:
            self.cache_hits += 1
            return self.cache_size[cache_key]  # type: ignore[return-value]

        self.total_queries += 1
        raw_response = self._call_api(user_msg)
        if raw_response is None:
            self.api_errors += 1
            return None

        action = self._parse_response(raw_response)
        if action is None:
            self.parse_failures += 1
            return None

        # Cache the result (evict oldest entry if full)
        if len(self.cache_size) >= self._max_cache:
            oldest = next(iter(self.cache_size))
            del self.cache_size[oldest]
        self.cache_size[cache_key] = action  # type: ignore[assignment]

        return action

    def record_transition(
        self,
        obs: np.ndarray,
        action: int,
        reward: float,
    ) -> None:
        """Accumulate (obs, action, reward) tuples for behavioral cloning."""
        self._obs_buf.append(obs.copy())
        self._act_buf.append(action)
        self._reward_buf.append(reward)

    def save_dataset(self, path: str) -> int:
        """
        Save the collected behavioral cloning dataset to disk.
        Returns the number of transitions saved.
        """
        if not self._obs_buf:
            logger.warning("LLMOracle.save_dataset: buffer is empty, nothing saved.")
            return 0
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        np.savez(
            path,
            observations=np.array(self._obs_buf, dtype=np.float32),
            actions=np.array(self._act_buf,      dtype=np.int64),
            rewards=np.array(self._reward_buf,    dtype=np.float32),
        )
        n = len(self._obs_buf)
        logger.info("LLMOracle: saved %d transitions to %s", n, path)
        return n

    def load_dataset(self, path: str) -> Tuple[np.ndarray, np.ndarray]:
        """Load a saved dataset and return (observations, actions)."""
        data = np.load(path)
        return data["observations"], data["actions"]

    def stats(self) -> Dict[str, Any]:
        return {
            "role":            self.role,
            "total_queries":   self.total_queries,
            "cache_hits":      self.cache_hits,
            "cache_hit_rate":  self.cache_hits / max(1, self.total_queries),
            "parse_failures":  self.parse_failures,
            "api_errors":      self.api_errors,
            "dataset_size":    len(self._obs_buf),
        }

    # ── Prompt construction ────────────────────────────────────────────────────

    def _format_user_message(
        self,
        observation: np.ndarray,
        env_state: Optional[Dict[str, Any]],
        cum_reward: float,
        max_steps: int,
    ) -> str:
        # De-normalise based on role
        if self.role == "attacker":
            kc   = round(float(observation[0]) * 2.0)
            step = round(float(observation[1]) * max_steps)
            return self._user_template.format(
                kill_chain   = f"{kc} ({'EXTERNAL' if kc==0 else 'USER_ACCESS' if kc==1 else 'ROOT_ACCESS'})",
                step         = step,
                max_steps    = max_steps,
                last_success = bool(observation[2] > 0.5),
                last_timeout = bool(observation[3] > 0.5),
                cum_reward   = cum_reward,
            )
        else:
            failed_logins     = round(float(observation[0]) * 50.0)
            suspicious_events = round(float(observation[1]) * 30.0)
            files_downloaded  = round(float(observation[4]) * 20.0)
            decoys_deployed   = round(float(observation[6]) * 5.0)
            is_rate_limited   = bool(observation[5] > 0.5)
            alerts_triggered  = round(float(observation[7]) * 10.0)
            step              = round(float(observation[3]) * max_steps)
            return self._user_template.format(
                failed_logins     = failed_logins,
                suspicious_events = suspicious_events,
                files_downloaded  = files_downloaded,
                decoys_deployed   = decoys_deployed,
                is_rate_limited   = is_rate_limited,
                alerts_triggered  = alerts_triggered,
                step              = step,
                max_steps         = max_steps,
                cum_reward        = cum_reward,
            )

    # ── LLM API calls ──────────────────────────────────────────────────────────

    def _call_api(self, user_message: str) -> Optional[str]:
        provider = self.config.get("provider", "ollama").lower()
        try:
            if provider == "anthropic":
                return self._call_anthropic(user_message)
            elif provider == "gemini":
                return self._call_gemini(user_message)
            elif provider == "ollama":
                # Works for any Ollama model: codellama, llama3, mistral, etc.
                return self._call_ollama(user_message)
            elif provider == "openai":
                return self._call_openai(user_message)
            else:
                logger.error("Unknown LLM provider: %s", provider)
                return None
        except Exception as exc:
            logger.warning("LLMOracle API call failed: %s", exc)
            return None

    def _call_anthropic(self, user_message: str) -> Optional[str]:
        api_key = self.config.get("api_key") or os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            logger.warning("ANTHROPIC_API_KEY not set")
            return None
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key":         api_key,
                "anthropic-version": "2023-06-01",
                "content-type":      "application/json",
            },
            json={
                "model":      self.config.get("model", "claude-haiku-4-5-20251001"),
                "max_tokens": 128,
                "system":     self._system_prompt,
                "messages":   [{"role": "user", "content": user_message}],
            },
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()["content"][0]["text"].strip()

    def _call_gemini(self, user_message: str) -> Optional[str]:
        """
        Google Gemini API — free tier available (gemini-1.5-flash recommended).
        Set your key via:  GEMINI_API_KEY=... python run_training.py ...
        Or put it in config.json under llm.api_key.

        To enable: set provider="gemini" and model="gemini-1.5-flash" in config.json.
        """
        api_key = (
            self.config.get("api_key")
            or os.environ.get("GEMINI_API_KEY")
            or os.environ.get("GOOGLE_API_KEY")
        )
        if not api_key:
            logger.warning("GEMINI_API_KEY (or GOOGLE_API_KEY) not set")
            return None
        model = self.config.get("model", "gemini-1.5-flash")
        # Gemini doesn't have a separate system role in the basic REST API,
        # so we prepend the system prompt to the user message.
        combined = f"{self._system_prompt}\n\n{user_message}"
        resp = requests.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
            params={"key": api_key},
            json={
                "contents": [
                    {"role": "user", "parts": [{"text": combined}]}
                ],
                "generationConfig": {
                    "temperature":    self.config.get("temperature", 0.3),
                    "maxOutputTokens": 128,
                    "stopSequences":  [],
                },
            },
            timeout=20,
        )
        resp.raise_for_status()
        candidates = resp.json().get("candidates", [])
        if not candidates:
            return None
        return candidates[0]["content"]["parts"][0]["text"].strip()

    def _call_ollama(self, user_message: str) -> Optional[str]:
        api_base = self.config.get("api_base", "http://localhost:11434")
        resp = requests.post(
            f"{api_base}/api/chat",
            json={
                "model":  self.config.get("model", "llama3.2:3b"),
                "stream": False,
                "options": {"temperature": self.config.get("temperature", 0.3)},
                "messages": [
                    {"role": "system",  "content": self._system_prompt},
                    {"role": "user",    "content": user_message},
                ],
            },
            timeout=30,
        )
        resp.raise_for_status()
        return resp.json()["message"]["content"].strip()

    def _call_openai(self, user_message: str) -> Optional[str]:
        api_key = self.config.get("api_key") or os.environ.get("OPENAI_API_KEY")
        if not api_key:
            logger.warning("OPENAI_API_KEY not set")
            return None
        resp = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={
                "model":       self.config.get("model", "gpt-4o-mini"),
                "max_tokens":  128,
                "temperature": self.config.get("temperature", 0.3),
                "messages": [
                    {"role": "system", "content": self._system_prompt},
                    {"role": "user",   "content": user_message},
                ],
            },
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"].strip()

    # ── Response parsing ───────────────────────────────────────────────────────

    def _parse_response(self, raw: str) -> Optional[int]:
        """
        Parse LLM response to a discrete action integer.
        Tries strict JSON parse first, then regex fallback.
        """
        # Strip markdown code fences if present
        text = raw.strip().strip("`")
        if text.startswith("json"):
            text = text[4:].strip()

        try:
            data = json.loads(text)
            action_name = data.get("action", "").lower().strip()
        except json.JSONDecodeError:
            # Fallback: look for any action name string in the response
            action_name = ""
            for name in self._action_vocab.values():
                if name in raw.lower():
                    action_name = name
                    break

        if action_name in ACTION_NAME_TO_INT:
            return ACTION_NAME_TO_INT[action_name]

        # Last resort: if the response contains a digit, try that
        for ch in text:
            if ch.isdigit():
                idx = int(ch)
                if 0 <= idx <= 9:
                    return idx

        logger.debug("LLMOracle: could not parse action from response: %s", raw[:120])
        return None

    @staticmethod
    def _hash(text: str) -> str:
        return hashlib.md5(text.encode()).hexdigest()


# ── Convenience: Wrap oracle as a predict()-compatible agent ──────────────────

class OracleAgent:
    """
    Wraps LLMOracle in the same .predict(obs) interface as scripted baselines
    so it can be dropped in as a curriculum opponent or behavioral cloning source.
    """

    def __init__(self, oracle: LLMOracle, fallback_agent=None):
        self.oracle = oracle
        self.fallback = fallback_agent
        self._cum_reward = 0.0

    def predict(self, observation, deterministic: bool = True):
        action = self.oracle.query(observation, cum_reward=self._cum_reward)
        if action is None and self.fallback is not None:
            action, _ = self.fallback.predict(observation, deterministic)
        elif action is None:
            action = np.random.randint(0, 10)
        return action, None

    def reset_episode(self):
        self._cum_reward = 0.0