/**
 * rlData.ts — live-first, artifact-fallback data access for the RL dashboards.
 *
 * The RL Flask API (:5001, proxied by Express at /api/rl/*) and the honeypot
 * Elasticsearch stack only run locally. On the hosted site there is no Flask,
 * so every RL read falls back to a committed snapshot under public/rl-artifacts/
 * (generated by src/server/rl/export_artifacts.py).
 *
 * Use fetchRL() for plain JSON reads. It returns { data, source } so the UI can
 * show whether it is looking at live data or a baked snapshot.
 */
import { API_BASE_URL } from "@/lib/api";

export type RLSource = "live" | "replay";

export interface RLResult<T> {
  data: T;
  source: RLSource;
}

/** Static snapshot served from public/rl-artifacts/ (Vite serves /public at root). */
const ARTIFACT_BASE = "/rl-artifacts";

/**
 * Fetch an RL JSON resource. Tries the live endpoint first; on network error,
 * non-OK status, or timeout, falls back to the committed artifact.
 *
 * @param endpoint     live path under the API root, e.g. "/api/rl/metrics/history"
 * @param artifactFile snapshot filename under /rl-artifacts, e.g. "metrics_history.json"
 */
export async function fetchRL<T>(
  endpoint: string,
  artifactFile: string,
  { timeoutMs = 4000 }: { timeoutMs?: number } = {},
): Promise<RLResult<T>> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    const res = await fetch(`${API_BASE_URL}${endpoint}`, {
      signal: controller.signal,
    });
    clearTimeout(timer);
    if (res.ok) {
      const data = (await res.json()) as T;
      return { data, source: "live" };
    }
  } catch {
    // fall through to the snapshot
  }

  const res = await fetch(`${ARTIFACT_BASE}/${artifactFile}`);
  if (!res.ok) {
    throw new Error(`No live RL backend and no snapshot for ${artifactFile}`);
  }
  return { data: (await res.json()) as T, source: "replay" };
}

/** Resolve the training-curves plot URL, preferring the live endpoint. */
export function rlPlotUrl(name = "training_progress"): string {
  return `${API_BASE_URL}/api/rl/plots/${name}`;
}

export function rlArtifactPlotUrl(file = "training_curves.png"): string {
  return `${ARTIFACT_BASE}/${file}`;
}

// ── Shared response shapes ────────────────────────────────────────────────

export interface MetricsHistory {
  iterations: number[];
  curriculum_levels: number[];
  att_win_rates: number[];
  def_win_rates: number[];
  att_elo: number[];
  def_elo: number[];
  timestamps: string[];
}

export interface MeanStd {
  mean: number | null;
  std: number | null;
}

export interface ExploitabilityRun {
  run: string;
  nashconv: number | null;
  att_exploitability: number | null;
  att_gap: number | null;
  def_exploitability: number | null;
  def_gap: number | null;
  equilibrium?: { att_win_rate: number; def_win_rate: number } | null;
}

export interface ExploitabilityReport {
  n_runs: number;
  nashconv: MeanStd;
  attacker: { exploitability: MeanStd; gap: MeanStd };
  defender: { exploitability: MeanStd; gap: MeanStd };
  runs: ExploitabilityRun[];
}

export interface LeaderboardEntry {
  agent: string;
  elo: number;
}
