import { useState, useRef } from "react";
import CyberpunkCard from "@/components/CyberpunkCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Loader2, AlertCircle, Upload, Copy, CheckCircle, Download } from "lucide-react";
import { API_BASE_URL } from "@/lib/api";

interface ROPGadget {
  offset: string;
  instructions: string;
  bytes: string;
  category: string;
}

interface ROPGadgetResult {
  architecture: string;
  gadgets: ROPGadget[];
  totalGadgets: number;
  categories: Record<string, number>;
  filename: string;
}

const CATEGORY_COLORS: Record<string, string> = {
  "pop-ret": "bg-red-500/20 text-red-400 border-red-500/30",
  "mov-ret": "bg-orange-500/20 text-orange-400 border-orange-500/30",
  "xor-ret": "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  "add-ret": "bg-green-500/20 text-green-400 border-green-500/30",
  "sub-ret": "bg-blue-500/20 text-blue-400 border-blue-500/30",
  "syscall": "bg-purple-500/20 text-purple-400 border-purple-500/30",
  "jmp-call": "bg-pink-500/20 text-pink-400 border-pink-500/30",
  "epilogue": "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  "misc": "bg-gray-500/20 text-gray-400 border-gray-500/30",
};

const ROPGadgetFinder = () => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [arch, setArch] = useState("x64");
  const [isScanning, setIsScanning] = useState(false);
  const [result, setResult] = useState<ROPGadgetResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState<string>("all");
  const [copied, setCopied] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setSelectedFile(file);
      setResult(null);
      setError(null);
    }
  };

  const scan = async () => {
    if (!selectedFile) return;
    setIsScanning(true);
    setResult(null);
    setError(null);

    try {
      const formData = new FormData();
      formData.append("file", selectedFile);
      formData.append("arch", arch);

      const response = await fetch(`${API_BASE_URL}/api/scan/rop-gadgets`, {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Scan failed");
      }

      setResult(await response.json());
    } catch (err: any) {
      setError(err.message || "Failed to scan binary");
    } finally {
      setIsScanning(false);
    }
  };

  const filteredGadgets = result?.gadgets.filter((g) => {
    const matchSearch = !search || g.instructions.toLowerCase().includes(search.toLowerCase()) || g.offset.includes(search);
    const matchCategory = activeCategory === "all" || g.category === activeCategory;
    return matchSearch && matchCategory;
  }) ?? [];

  const exportAsPython = () => {
    if (!result) return;
    const lines = filteredGadgets.map((g) => `# ${g.instructions}\nrop.search(byte="${g.bytes.replace(/\s/g, "")}")`).join("\n");
    const content = `# ROP Gadgets from ${result.filename}\n# Architecture: ${result.architecture}\n# Generated by Cyber-X\n\n${lines}`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "rop_gadgets.py";
    a.click();
  };

  const copyGadgets = () => {
    const text = filteredGadgets.map((g) => `${g.offset}: ${g.instructions}`).join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <CyberpunkCard title="ROP GADGET FINDER">
      <div className="space-y-6">
        <div className="glass-panel rounded p-4 space-y-3">
          <div
            className="border-2 border-dashed border-cyber-cyan/30 rounded p-6 text-center cursor-pointer hover:border-cyber-cyan/60 transition-colors"
            onClick={() => fileInputRef.current?.click()}
          >
            <Upload className="w-8 h-8 text-cyber-cyan/50 mx-auto mb-2" />
            <p className="text-cyber-cyan text-sm">{selectedFile ? selectedFile.name : "Click to select binary (ELF, PE, raw)"}</p>
            {selectedFile && <p className="text-gray-500 text-xs mt-1">{(selectedFile.size / 1024).toFixed(1)} KB</p>}
          </div>
          <input ref={fileInputRef} type="file" className="hidden" onChange={handleFileSelect} />

          <div>
            <label className="block text-xs text-cyber-cyan mb-1 tracking-wide">ARCHITECTURE</label>
            <div className="flex gap-2">
              {["x86", "x64", "arm"].map((a) => (
                <button
                  key={a}
                  onClick={() => setArch(a)}
                  className={`px-3 py-1 text-xs font-bold rounded border transition-colors ${
                    arch === a ? "bg-cyber-red text-white border-cyber-red" : "bg-cyber-cyan/10 text-cyber-cyan border-cyber-cyan/30 hover:bg-cyber-cyan/20"
                  }`}
                >
                  {a.toUpperCase()}
                </button>
              ))}
            </div>
          </div>

          <Button
            onClick={scan}
            disabled={isScanning || !selectedFile}
            className="w-full bg-cyber-red hover:bg-cyber-red/80 text-white font-bold"
          >
            {isScanning ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />SCANNING GADGETS...</> : "FIND ROP GADGETS"}
          </Button>
        </div>

        {error && (
          <div className="flex items-center gap-2 p-3 bg-red-500/10 border border-red-500/30 rounded text-red-400 text-sm">
            <AlertCircle className="w-4 h-4 shrink-0" />
            {error}
          </div>
        )}

        {result && (
          <div className="space-y-4">
            {/* Summary */}
            <div className="glass-panel rounded p-4">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-cyber-cyan font-bold tracking-wide">RESULTS</h3>
                <div className="flex gap-2">
                  <Button size="sm" className="bg-cyber-cyan/20 hover:bg-cyber-cyan/30 text-cyber-cyan border border-cyber-cyan/30" onClick={copyGadgets}>
                    {copied ? <><CheckCircle className="w-3 h-3 mr-1" />Copied!</> : <><Copy className="w-3 h-3 mr-1" />Copy</>}
                  </Button>
                  <Button size="sm" className="bg-cyber-cyan/20 hover:bg-cyber-cyan/30 text-cyber-cyan border border-cyber-cyan/30" onClick={exportAsPython}>
                    <Download className="w-3 h-3 mr-1" />Python
                  </Button>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div><span className="text-gray-400">File:</span> <span className="text-cyber-cyan font-mono">{result.filename}</span></div>
                <div><span className="text-gray-400">Arch:</span> <span className="text-cyber-cyan font-mono">{result.architecture}</span></div>
                <div><span className="text-gray-400">Total gadgets:</span> <span className="text-cyber-cyan font-mono">{result.totalGadgets}</span></div>
              </div>
            </div>

            {/* Category filters */}
            <div className="flex flex-wrap gap-2">
              <button
                onClick={() => setActiveCategory("all")}
                className={`px-2 py-0.5 text-xs font-bold rounded border ${activeCategory === "all" ? "bg-cyber-red text-white border-cyber-red" : "bg-cyber-cyan/10 text-cyber-cyan border-cyber-cyan/30"}`}
              >
                ALL ({result.totalGadgets})
              </button>
              {Object.entries(result.categories).map(([cat, count]) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={`px-2 py-0.5 text-xs font-bold rounded border transition-colors ${
                    activeCategory === cat
                      ? "bg-cyber-red text-white border-cyber-red"
                      : (CATEGORY_COLORS[cat] || "bg-gray-500/20 text-gray-400 border-gray-500/30")
                  }`}
                >
                  {cat} ({count})
                </button>
              ))}
            </div>

            {/* Search */}
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search instructions or offset..."
              className="bg-black/50 border-cyber-cyan/30 text-cyber-cyan"
            />

            <p className="text-gray-500 text-xs">{filteredGadgets.length} gadgets shown</p>

            {/* Gadget table */}
            <div className="space-y-1 max-h-96 overflow-y-auto">
              {filteredGadgets.map((g, i) => (
                <div key={i} className="flex items-center gap-3 px-3 py-2 hover:bg-black/20 rounded border border-transparent hover:border-cyber-cyan/10">
                  <span className="text-gray-500 font-mono text-xs w-24 shrink-0">{g.offset}</span>
                  <code className="text-cyber-cyan font-mono text-xs flex-1">{g.instructions}</code>
                  <span className={`px-1.5 py-0.5 rounded text-xs border shrink-0 ${CATEGORY_COLORS[g.category] || "bg-gray-500/20 text-gray-400 border-gray-500/30"}`}>
                    {g.category}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </CyberpunkCard>
  );
};

export default ROPGadgetFinder;
